# Generated by Django 4.2.15 on 2024-08-31 11:28

from django.db import migrations, models
import domains.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('private_key', models.FileField(blank=True, null=True, upload_to='keys/')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/', validators=[domains.models.validate_certificate])),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('cloudflare_api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
