# Generated by Django 4.2.15 on 2024-08-31 11:59

from django.db import migrations
import domains.models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='certificate',
            field=domains.models.LongTextField(blank=True, null=True, validators=[domains.models.validate_certificate]),
        ),
        migrations.AlterField(
            model_name='domain',
            name='private_key',
            field=domains.models.LongTextField(blank=True, null=True),
        ),
    ]
