# Generated by Django 4.2.15 on 2024-08-31 16:56

from django.db import migrations
import domains.models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_alter_domain_certificate_alter_domain_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='chain',
            field=domains.models.LongTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='fullchain',
            field=domains.models.LongTextField(blank=True, null=True),
        ),
    ]
